# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0rx4c2G6QB1UKgmNjVJ8PYunhInd8uN
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from numba import njit

# ==========================================
# 1. CACHED DATA FETCHING (HOLIDAY RESILIENT)
# ==========================================
@st.cache_data(ttl=86400)
def fetch_and_prep_data(start_date='2000-01-01', end_date='2025-12-31'):
    # yfinance outputs multiple tickers in strict alphabetical order
    tickers = ['000001.SS', 'AGG', 'AOA', 'AOK', 'AOR', '^GSPC', '^SET.BK']
    data = yf.download(tickers, start=start_date, end=end_date)['Close']

    # FIX: Forward fill cross-border holiday gaps so datasets align without dropping rows
    data = data.ffill().bfill()
    data_change = np.log(data / data.shift(1)).dropna()

    bear_data = data_change.loc['2007-01-01':'2010-01-01']
    bull_data = data_change.loc['2011-01-01':'2019-01-01']

    bfr_mean_returns = data_change.mean().values
    variances = np.diag(data_change.cov().values)
    mean_returns = bfr_mean_returns - (variances / 2)

    bull_cov = bull_data.cov().values
    bear_cov = bear_data.cov().values

    return mean_returns, bull_cov, bear_cov

# ==========================================
# 2. ALIGNED NUMBA SIMULATION ENGINE
# ==========================================
@njit
def run_fast_simulations(num_simulations, duration, initial_amount,
                         china_w, bond_w, agg_w, con_w, mod_w, us_w, thai_w,
                         savings_weight, pure_cash_weight, saving_daily_return,
                         bull_multipliers, bear_multipliers, withdrawal_amount, inserted_funds):

    portfolio_simulations = np.zeros((duration, num_simulations))
    trials_failed = 0

    for sim in range(num_simulations):
        # Initial balances mapping strictly to alphabetical assets
        china_stocks = initial_amount * china_w
        bond_mutual = initial_amount * bond_w
        agg_mutual = initial_amount * agg_w
        con_mutual = initial_amount * con_w
        mod_mutual = initial_amount * mod_w
        us_stocks = initial_amount * us_w
        thai_stocks = initial_amount * thai_w
        savings = initial_amount * savings_weight
        pure_cash = initial_amount * pure_cash_weight

        is_bear = np.random.rand() < 0.5

        for day in range(duration):
            if is_bear:
                mults = bear_multipliers[day, sim]
                if np.random.rand() < 0.1: is_bear = False
            else:
                mults = bull_multipliers[day, sim]
                if np.random.rand() < 0.05: is_bear = True

            # Apply returns directly to matching matrix columns
            china_stocks *= mults[0]
            bond_mutual *= mults[1]
            agg_mutual *= mults[2]
            con_mutual *= mults[3]
            mod_mutual *= mults[4]
            us_stocks *= mults[5]
            thai_stocks *= mults[6]
            savings *= saving_daily_return

            if day > 0 and day % 21 == 0:
                china_stocks += inserted_funds * china_w
                bond_mutual += inserted_funds * bond_w
                agg_mutual += inserted_funds * agg_w
                con_mutual += inserted_funds * con_w
                mod_mutual += inserted_funds * mod_w
                us_stocks += inserted_funds * us_w
                thai_stocks += inserted_funds * thai_w
                savings += inserted_funds * savings_weight

                if day > 2520:
                    if pure_cash >= withdrawal_amount: pure_cash -= withdrawal_amount
                    elif savings >= withdrawal_amount: savings -= withdrawal_amount
                    elif agg_mutual >= withdrawal_amount: agg_mutual -= withdrawal_amount
                    elif mod_mutual >= withdrawal_amount: mod_mutual -= withdrawal_amount
                    elif con_mutual >= withdrawal_amount: con_mutual -= withdrawal_amount
                    elif bond_mutual >= withdrawal_amount: bond_mutual -= withdrawal_amount
                    elif us_stocks >= withdrawal_amount: us_stocks -= withdrawal_amount
                    elif china_stocks >= withdrawal_amount: china_stocks -= withdrawal_amount
                    elif thai_stocks >= withdrawal_amount: thai_stocks -= withdrawal_amount
                    else:
                        trials_failed += 1
                        break

            portfolio_simulations[day, sim] = (china_stocks + bond_mutual + agg_mutual +
                                               con_mutual + mod_mutual + us_stocks +
                                               thai_stocks + savings + pure_cash)

    return portfolio_simulations, trials_failed

# ==========================================
# 3. STREAMLIT UI LAYOUT
# ==========================================
st.set_page_config(page_title="Production Portfolio Engine", layout="wide")
st.title("Monte Carlo Asset Allocation Simulator")

with st.spinner("Streaming integrated market histories..."):
    mean_returns, bull_cov, bear_cov = fetch_and_prep_data()

st.sidebar.header("Capital Controls")
initial_amount = st.sidebar.number_input("Principal Amount (THB)", value=3000000, step=100000)
inserted_funds = st.sidebar.number_input("Monthly Contribution", value=10000, step=1000)
withdrawal_pct = st.sidebar.number_input("Target Annual Withdrawal Rate (%)", value=4.0, step=0.1) / 100
withdrawal_amount = (initial_amount * withdrawal_pct) / 12

st.sidebar.header("Asset Distributions")
savings_weight = st.sidebar.slider("Risk-Free Savings Weight", 0.0, 1.0, 0.1)
us_weight = st.sidebar.slider("S&P 500 Index Weight", 0.0, 1.0, 0.1)
thai_weight = st.sidebar.slider("SET Index Weight", 0.0, 1.0, 0.2)
china_weight = st.sidebar.slider("SSE Composite Weight", 0.0, 1.0, 0.1)
bond_mut = st.sidebar.slider("AGG Bond ETF Weight", 0.0, 1.0, 0.1)
agg_mut = st.sidebar.slider("AOA Aggressive Target Allocation", 0.0, 1.0, 0.1)
mod_mut = st.sidebar.slider("AOR Moderate Target Allocation", 0.0, 1.0, 0.1)
con_mut = st.sidebar.slider("AOK Conservative Target Allocation", 0.0, 1.0, 0.1)

total_weight = sum([savings_weight, us_weight, thai_weight, china_weight, bond_mut, agg_mut, mod_mut, con_mut])
pure_cash_weight = 1.0 - total_weight

if total_weight > 1.0:
    st.sidebar.error(f"Asset limits exceeded! Net Allocation: {total_weight:.2f}")
    st.stop()

if st.button("Execute Tensor Simulation"):
    duration = 7560
    num_sims = 1000

    with st.spinner("Constructing cross-border covariance paths..."):
        bull_chol = np.linalg.cholesky(bull_cov)
        bear_chol = np.linalg.cholesky(bear_cov)

        rand_normals = np.random.standard_normal((duration, num_sims, len(mean_returns)))

        bull_returns = rand_normals @ bull_chol.T + mean_returns
        bear_returns = rand_normals @ bear_chol.T + mean_returns

        # Expense ratios realigned strictly to match alphabetical assets
        # China, AGG, AOA, AOK, AOR, US, Thai
        expense_ratios = np.array([0.005, 0.001, 0.003, 0.003, 0.003, 0.001, 0.002])
        daily_fee_drag = (1 - expense_ratios) ** (1 / 252)

        bull_multipliers = np.exp(bull_returns) * daily_fee_drag
        bear_multipliers = np.exp(bear_returns) * daily_fee_drag

    with st.spinner("Processing Monte Carlo matrices..."):
        saving_daily_return = (1 + 0.025) ** (1 / 252)

        sim_results, trials_failed = run_fast_simulations(
            num_sims, duration, initial_amount,
            china_weight, bond_mut, agg_mut, con_mut, mod_mut, us_weight, thai_weight,
            savings_weight, pure_cash_weight, saving_daily_return,
            bull_multipliers, bear_multipliers, withdrawal_amount, inserted_funds
        )

    st.subheader("Performance Metrics")
    col1, col2, col3 = st.columns(3)
    ending_values = sim_results[-1, :]

    col1.metric("Median Portfolio Yield", f"THB {np.percentile(ending_values, 50):,.2f}")
    col2.metric("Portfolio Insolvency Rate", f"{(trials_failed/num_sims)*100:.1f}%")

    avg_inflation_rate = 0.0177
    adj_median = np.percentile(ending_values, 50) / ((1 + avg_inflation_rate) ** (duration / 252))
    col3.metric("Real Purchasing Power Value", f"THB {adj_median:,.2f}")

    fig, ax = plt.subplots(figsize=(10, 4.5))
    percentiles = np.percentile(sim_results, [10, 25, 50, 75, 90], axis=1)

    ax.plot(percentiles[0], label='10th Percentile Risk Bounds', color='red', linestyle='--')
    ax.plot(percentiles[1], label='25th Percentile Downside', color='orange', linestyle=':')
    ax.plot(percentiles[2], label='50th Percentile Median Path', color='black', linewidth=2)
    ax.plot(percentiles[3], label='75th Percentile Upside', color='green', linestyle=':')

    ax.set_title('Decile-Bounded Structural Portfolio Projections')
    ax.set_xlabel('Trading Horizon (Days)')
    ax.set_ylabel('Total Portfolio Capitalization (THB)')
    ax.legend(loc='upper left')
    ax.grid(True, alpha=0.25)

    st.pyplot(fig)