# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1192eau8Gwhpu4wiZKgWV-HVQtS-QvzkB
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numba import njit
import random
from scipy.stats import multivariate_t
from scipy.stats import t
from numba import njit

st.set_page_config(
    page_title="Monte Carlo Retirement Simulator",
    layout="wide"
)

st.title("Monte Carlo Portfolio Simulator")

st.write("This simulator is meant to help gague model effectiveness and may not always be reliable, hence, model outputs is not financial advice. "
            " Please interpret results with caution as model outputs may not reflect reality.")
initial_amount = st.sidebar.number_input(
    "Initial Amount",
    0,
    100000000,
    1000000,
    1000000
)

monthly_contribution = st.sidebar.number_input(
    "Monthly Contribution",
    0,
    300000,
    10000
)

num_simulations = st.sidebar.slider(
    "Simulations",
    100,
    1000,
    500,
    10
)

withdrawal = st.sidebar.number_input(
    "Annual Withdrawal",
    0,
    3000000,
    10000

)

avg_inflation_rate = st.sidebar.slider(
    "Average Inflation Rate",
    0.0,
    0.15,
    0.02,
    0.01
)

def run_index_model():
  @st.cache_data
  def load_market_data():

      return pd.read_parquet(
          "1.parquet"
      )
  @st.cache_data
  def build_market_stats():

      combined_data = load_market_data()

      bear_data = combined_data.loc[
          "2005-01-01":"2009-04-01"
      ]

      bull_data = combined_data.loc[
          "2010-03-01":"2019-01-01"
      ]

      bull_mean = bull_data.mean()
      bear_mean = bear_data.mean()

      bull_cov = bull_data.cov()
      bear_cov = bear_data.cov()

      bull_var = np.diag(bull_cov)
      bear_var = np.diag(bear_cov)

      bull_adj = bull_mean - bull_var / 2
      bear_adj = bear_mean - bear_var / 2

      return (
          bull_adj.values,
          bear_adj.values,
          bull_cov.values,
          bear_cov.values
      )
  st.sidebar.subheader("Portfolio")

  us_weight = st.sidebar.slider(
      "US Equity",
      0.0,
      1.0,
      0.20,
      0.01
  )

  thai_weight = st.sidebar.slider(
      "Thai Equity",
      0.0,
      1.0,
      0.20,
      0.01
  )

  china_weight = st.sidebar.slider(
      "Chinese Equity",
      0.0,
      1.0,
      0.10,
      0.01
  )

  bond_weight = st.sidebar.slider(
      "Bond Fund",
      0.0,
      1.0,
      0.20,
      0.01
  )

  agg_weight = st.sidebar.slider(
      "Aggressive Hybrid Fund",
      0.0,
      1.0,
      0.10,
      0.01
  )

  mod_weight = st.sidebar.slider(
      "Moderate Hybrid Fund",
      0.0,
      1.0,
      0.10,
      0.01
  )

  cons_weight = st.sidebar.slider(
      "Conservative Hybrid Fund",
      0.0,
      1.0,
      0.05,
      0.01
  )

  savings_weight = st.sidebar.slider(
      "Savings",
      0.0,
      1.0,
      0.05,
      0.01
  )
  total_weight = (
      us_weight +
      thai_weight +
      china_weight +
      bond_weight +
      agg_weight +
      mod_weight +
      cons_weight +
      savings_weight
  )

  st.sidebar.write(
      f"Total Weight: {total_weight:.2f}"
  )

  if total_weight > 1:
      st.error(
          "Weights exceed 100%"
      )
      st.stop()
  run = st.button(
      "Run Simulation"
  )
  @njit(cache=True)
  def run_path(
      bull_mult,
      bear_mult,
      duration,
      matured_duration,
      assets,
      savings_account,
      pure_cash_amt,
      contribution_weights,
      inserted_funds,
      savings_account_weight,
      saving_daily_return,
      withdrawal_percentage,
      daily_hazard_rate,
      pure_cash_weight,

      us_gov_bond,
      us_inv_bond,
      us_spec_bond,
      thai_gov_bond,
      thai_inv_bond,
      thai_spec_bond,

      us_gov_bond_daily_return,
      us_inv_bond_daily_return,
      us_spec_bond_daily_return,
      thai_gov_bond_daily_return,
      thai_inv_bond_daily_return,
      thai_spec_bond_daily_return
  ):

      portfolio_path = np.zeros(duration, dtype=np.float32)

      thai_default_events = False
      us_default_events = False
      matured = False

      market = np.random.randint(0, 2)

      failed = 0

      for day in range(duration):

          if market == 1:

              current = bear_mult[day]

              if np.random.random() < 0.05:
                  market = 0

          else:

              current = bull_mult[day]

              if np.random.random() < 0.02:
                  market = 1

          assets *= current

          savings_account *= saving_daily_return

          if day < 2520:

              if (not thai_default_events) and np.random.random() < daily_hazard_rate:
                  thai_default_events = True

              if (not us_default_events) and np.random.random() < daily_hazard_rate:
                  us_default_events = True

          if not matured:

              us_gov_bond *= us_gov_bond_daily_return
              us_inv_bond *= us_inv_bond_daily_return
              thai_gov_bond *= thai_gov_bond_daily_return
              thai_inv_bond *= thai_inv_bond_daily_return

              if thai_default_events:
                  thai_spec_bond = 0.0
              else:
                  thai_spec_bond *= thai_spec_bond_daily_return

              if us_default_events:
                  us_spec_bond = 0.0
              else:
                  us_spec_bond *= us_spec_bond_daily_return

          if day % 21 == 0:

              if day < 2520:
                  pure_cash_amt += inserted_funds*pure_cash_weight
                  assets += inserted_funds * contribution_weights
                  savings_account += inserted_funds * savings_account_weight

              else:

                  withdrawal_amount = withdrawal_percentage / 12.0

                  if pure_cash_amt >= withdrawal_amount:

                      pure_cash_amt -= withdrawal_amount

                  elif savings_account >= withdrawal_amount:

                      savings_account -= withdrawal_amount

                  elif assets[4] >= withdrawal_amount:

                      assets[4] -= withdrawal_amount

                  elif assets[5] >= withdrawal_amount:

                      assets[5] -= withdrawal_amount

                  elif assets[6] >= withdrawal_amount:

                      assets[6] -= withdrawal_amount

                  elif assets[3] >= withdrawal_amount:

                      assets[3] -= withdrawal_amount

                  elif assets[0] >= withdrawal_amount:

                      assets[0] -= withdrawal_amount

                  elif assets[2] >= withdrawal_amount:

                      assets[2] -= withdrawal_amount

                  elif assets[1] >= withdrawal_amount:

                      assets[1] -= withdrawal_amount

                  else:

                      failed = 1
                      break

          if (not matured) and day > 0 and day % matured_duration == 0:

              matured = True

              pure_cash_amt += (
                  us_gov_bond
                  + us_inv_bond
                  + thai_gov_bond
                  + thai_inv_bond
                  + thai_spec_bond
                  + us_spec_bond
              )

              us_gov_bond = 0.0
              us_inv_bond = 0.0
              thai_gov_bond = 0.0
              thai_inv_bond = 0.0
              thai_spec_bond = 0.0
              us_spec_bond = 0.0

          portfolio_path[day] = (
              assets[0]
              + assets[1]
              + assets[2]
              + assets[3]
              + assets[4]
              + assets[5]
              + assets[6]
              + savings_account
              + pure_cash_amt
          )

      return portfolio_path,failed
  us_gov_bond_weight = 0.0
  us_inv_bond_weight = 0.0
  us_spec_bond_weight = 0.0

  thai_gov_bond_weight = 0.0
  thai_inv_bond_weight = 0.0
  thai_spec_bond_weight = 0.0
  if run:

      with st.spinner(
          "Running simulation..."
      ):
        expense_ratios = np.array([
        0.001,
        0.002,
        0.005,
        0.001,
        0.003,
        0.003,
        0.003
        ])

        daily_fee_drag = (1 - expense_ratios) ** (1/252)
        bull_adj_return, bear_adj_return, bull_cov_matrix, bear_cov_matrix = build_market_stats()
        stock_allocations = np.array([
          us_weight,
          thai_weight,
          china_weight
          ])

        bond_mutualfund_allocation = bond_weight
        hybrid_mutualfund_aggresive_allocation = agg_weight
        hybrid_mutualfund_moderate_allocation = mod_weight
        hybrid_mutualfund_conservative_allocation = cons_weight
        duration = 7560
        portfolio_simulations = np.zeros(
          (duration, num_simulations),
          dtype=np.float32
        )
        duration = 7560
        trials_failed = 0
        saving_returns = 0.0175
        saving_daily_return = (1 + saving_returns) ** (1/252)
        withdrawal_percentage = withdrawal
        contribution_weights = np.array([
          us_weight,
          thai_weight,
          china_weight,
          bond_weight,
          agg_weight,
          mod_weight,
          cons_weight
        ], dtype=np.float64)
        inserted_funds = monthly_contribution

        daily_hazard_rate = 0.00011

        total_stock_weight = (
          us_weight +
          thai_weight +
          china_weight
      )

        total_mutualfund_weight = (
          bond_weight +
          agg_weight +
          mod_weight +
          cons_weight
        )

        us_gov_bond_return = 0.04
        us_inv_bond_return = 0.05
        us_spec_bond_return = 0.08

        thai_gov_bond_return = 0.045
        thai_inv_bond_return = 0.05
        thai_spec_bond_return = 0.08

        total_bond_weight = 0.0

        savings_account_weight = savings_weight
        for sim in range(num_simulations):
          matured = False
          matured_duration = np.random.randint(504,2520)
          bull_returns = np.random.multivariate_normal(bull_adj_return, bull_cov_matrix, duration)
          df = 6
          scale_factor = np.sqrt(df / np.random.chisquare(df, duration))

          bull_daily_stock_returns_log = bull_returns * scale_factor[:, np.newaxis]

          bull_daily_stock_multipliers = np.exp(bull_daily_stock_returns_log) * daily_fee_drag
    #bear

          bear_returns = np.random.multivariate_normal(bear_adj_return, bear_cov_matrix, duration)
          df = 6
          scale_factor = np.sqrt(df / np.random.chisquare(df, duration))

          bear_daily_stock_returns_log = bear_returns * scale_factor[:, np.newaxis]


          bear_daily_stock_multipliers = np.exp(bear_daily_stock_returns_log) * daily_fee_drag

          assets = np.array([
            initial_amount * stock_allocations[0],
            initial_amount * stock_allocations[1],
            initial_amount * stock_allocations[2],
            initial_amount * bond_mutualfund_allocation,
            initial_amount * hybrid_mutualfund_aggresive_allocation,
            initial_amount * hybrid_mutualfund_moderate_allocation,
            initial_amount * hybrid_mutualfund_conservative_allocation
          ], dtype=np.float64)
          savings_account = initial_amount * savings_account_weight

          us_gov_bond = initial_amount * us_gov_bond_weight
          us_inv_bond = initial_amount * us_inv_bond_weight
          us_spec_bond = initial_amount * us_spec_bond_weight
          thai_gov_bond = initial_amount * thai_gov_bond_weight
          thai_inv_bond = initial_amount * thai_inv_bond_weight
          thai_spec_bond = initial_amount * thai_spec_bond_weight

          pure_cash = max(0,1 - total_bond_weight - total_stock_weight - total_mutualfund_weight - savings_account_weight)
          pure_cash_amt = initial_amount * pure_cash


    # Reset bond daily returns back to initial at the start of each simulation iteration
          us_gov_bond_daily_return = (1+us_gov_bond_return)**(1/252)
          us_inv_bond_daily_return = (1+us_inv_bond_return)**(1/252)
          thai_gov_bond_daily_return = (1+thai_gov_bond_return)**(1/252)
          thai_inv_bond_daily_return = (1+thai_inv_bond_return)**(1/252)
          thai_spec_bond_daily_return = (1+thai_spec_bond_return)**(1/252)
          us_spec_bond_daily_return = (1+us_spec_bond_return)**(1/252)


          portfolio_path, failed = run_path(
            bull_daily_stock_multipliers,
            bear_daily_stock_multipliers,
            duration,
            matured_duration,
            assets,
            savings_account,
            pure_cash_amt,
            contribution_weights,
            inserted_funds,
            savings_account_weight,
            saving_daily_return,
            withdrawal_percentage,
            daily_hazard_rate,
            pure_cash,

            us_gov_bond,
            us_inv_bond,
            us_spec_bond,
            thai_gov_bond,
            thai_inv_bond,
            thai_spec_bond,

            us_gov_bond_daily_return,
            us_inv_bond_daily_return,
            us_spec_bond_daily_return,
            thai_gov_bond_daily_return,
            thai_inv_bond_daily_return,
            thai_spec_bond_daily_return
          )

          portfolio_simulations[:, sim] = portfolio_path

          trials_failed += failed


      percentiles = np.percentile(
          portfolio_simulations,
          [10,25,50,75,90],
          axis=1
      )
      fig, ax = plt.subplots(
          figsize=(12,7)
      )

      ax.plot(percentiles[0], label="10th")
      ax.plot(percentiles[1], label="25th")
      ax.plot(percentiles[2], label="50th")
      ax.plot(percentiles[3], label="75th")
      ax.plot(percentiles[4], label="90th")

      ax.legend()

      ax.set_title(
          "Portfolio Projection"
      )

      ax.set_xlabel(
          "Days"
      )

      ax.set_ylabel(
          "THB"
      )

      from matplotlib.ticker import FuncFormatter

      ax.yaxis.set_major_formatter(
        FuncFormatter(lambda x, pos: f"฿{x/1_000_000:.1f}M")
        )

      ax.set_ylabel("Portfolio Value (Million THB)")

      ax.grid(True)

      st.pyplot(fig)

      c1,c2,c3 = st.columns(3)
      ending_values = portfolio_simulations[-1, :]

      median = np.percentile(
        ending_values,
        50
      )

      c2.metric(
          "Median",
          f"฿{median/((1+avg_inflation_rate)**(duration/252)):,.0f}"
      )

      failure_rate = (
          trials_failed /
          num_simulations
      ) * 100

      st.metric(
          "Portfolio Failure Rate",
          f"{failure_rate:.2f}%"
      )

      success_rate = np.mean(
      (num_simulations-trials_failed)/num_simulations
      ) * 100

      c1.metric(
      "Capital Preserved",
      f"{success_rate:.1f}%"
      )
def run_company_model():
  days = 7560
  @st.cache_data
  def get_data():
          return pd.read_parquet(
          "2.parquet"
      )
  @st.cache_data
  def build_matrices():
    combined_data = get_data()
    bond_vol = combined_data["bond"].std()
    equity_vol = combined_data["equity"].std()
    cmod_vol = combined_data["cmod"].std()
    return bond_vol, equity_vol, cmod_vol
  bond_vol, equity_vol, cmod_vol = build_matrices()
  kkpplus_alloc = st.sidebar.slider(
      "KKP Plus",
      0.0,
      1.0,
      0.10,
      0.01
  )

  kkpcash_alloc = st.sidebar.slider(
      "KKP Cash",
      0.0,
      1.0,
      0.10,
      0.01
  )

  kfa_alloc = st.sidebar.slider(
      "KFAFIX",
      0.0,
      1.0,
      0.10,
      0.01
  )

  ugi_alloc = st.sidebar.slider(
      "UGISFX",
      0.0,
      1.0,
      0.10,
      0.01
  )

  gqg_alloc = st.sidebar.slider(
      "ESGQG",
      0.0,
      1.0,
      0.10,
      0.01
  )

  gtech_alloc = st.sidebar.slider(
      "ESGTECH",
      0.0,
      1.0,
      0.10,
      0.01
  )

  eae_alloc = st.sidebar.slider(
      "ESEAE",
      0.0,
      1.0,
      0.10,
      0.01
  )

  ktprecious_alloc = st.sidebar.slider(
      "KTPRECIOUS",
      0.0,
      1.0,
      0.10,
      0.01
  )
  total_alloc = (
    kkpplus_alloc +
    kkpcash_alloc +
    kfa_alloc +
    ugi_alloc +
    gqg_alloc +
    gtech_alloc +
    eae_alloc +
    ktprecious_alloc
  )

  if total_alloc > 1:
    st.error("Allocations exceed 100%")
    st.stop()
  run = st.button(
    "Run Simulation"
  )
  if run:

    with st.spinner("Running simulation..."):

      @njit(cache=True)
      def sim_path(
        kfa_returns,
        ugi_returns,
        gqg_returns,
        kkpplus_returns,
        kkpcash_returns,
        gtech_returns,
        eae_returns,
        ktp_returns,
        duration,
        inserted_funds,
        yearly_withdrawals,

        gqg_amt,
        kkpplus_amt,
        kkpcash_amt,
        kfa_amt,
        ugi_amt,
        gtech_amt,
        eae_amt,
        ktp_amt,
        savings_amt,

        kkpplus_alloc,
        kkpcash_alloc,
        kfa_alloc,
        ugi_alloc,
        gqg_alloc,
        gtech_alloc,
        eae_alloc,
        ktprecious_alloc,
        savings_alloc
      ):
        portfolio_paths = np.zeros(duration)
        failed = 0 # Initialize failed variable
        for day in range(duration):
          gqg_amt = gqg_amt * (gqg_returns[day]) # Changed kfa_returns to gqg_returns
          gtech_amt = gtech_amt *(gtech_returns[day])
          eae_amt = eae_amt *(eae_returns[day])
          ktp_amt = ktp_amt * (ktp_returns[day])
          ugi_amt = ugi_amt * (ugi_returns[day])
          kkpplus_amt = kkpplus_amt * (kkpplus_returns[day])
          kkpcash_amt = kkpcash_amt * (kkpcash_returns[day])
          kfa_amt = kfa_amt * (kfa_returns[day])
          savings_amt = savings_amt
          if day < 2520 and day % 21 ==0:
            kkpplus_amt += inserted_funds*kkpplus_alloc
            kkpcash_amt += inserted_funds*kkpcash_alloc
            kfa_amt += inserted_funds*kfa_alloc
            ugi_amt += inserted_funds*ugi_alloc
            gqg_amt += inserted_funds * gqg_alloc
            gtech_amt += inserted_funds * gtech_alloc
            eae_amt += inserted_funds * eae_alloc
            ktp_amt += inserted_funds * ktprecious_alloc
            savings_amt += inserted_funds * savings_alloc
          if day > 2520 and day %21 ==0:
            withdrawal_amount = yearly_withdrawals/12
            if savings_amt - withdrawal_amount > 0:
              savings_amt = savings_amt-withdrawal_amount
            elif kfa_amt - withdrawal_amount > 0:
              kfa_amt = kfa_amt - withdrawal_amount
            elif ugi_amt - withdrawal_amount > 0:
              ugi_amt = ugi_amt - withdrawal_amount
            elif kkpplus_amt - withdrawal_amount > 0:
              kkpplus_amt = kkpplus_amt - withdrawal_amount
            elif kkpcash_amt - withdrawal_amount > 0:
              kkpcash_amt = kkpcash_amt - withdrawal_amount
            elif gqg_amt - withdrawal_amount > 0:
              gqg_amt = gqg_amt - withdrawal_amount
            elif gtech_amt - withdrawal_amount > 0:
              gtech_amt = gtech_amt - withdrawal_amount
            elif eae_amt - withdrawal_amount > 0:
              eae_amt = eae_amt - withdrawal_amount
            elif ktp_amt - withdrawal_amount > 0:
              ktp_amt = ktp_amt - withdrawal_amount
            else:
              failed = 1
              break
          if day % 252 == 0:
            kkpplus_amt = kkpplus_amt * (1-kkpplus_managementfee)
            kkpcash_amt = kkpcash_amt * (1-kkpcash_managementfee)
            kfa_amt = kfa_amt * (1-kfa_mangementfee)
            ugi_amt = ugi_amt * (1-ugisfx_managementfee)
            gqg_amt = gqg_amt * (1-esgqg_managementfee)
            gtech_amt = gtech_amt * (1-esgtech_managementfee)
            eae_amt = eae_amt * (1-eseae_managementfee)
            ktp_amt = ktp_amt * (1-ktprecious_managementfee)
          portfolio_paths[day] = (
              kkpplus_amt + kkpcash_amt + kfa_amt + ugi_amt + gqg_amt + gtech_amt + eae_amt + ktp_amt + savings_amt
              )

        return portfolio_paths,failed
      days = 7560
      df = 10

      portfolio_simulations = np.zeros(
        (days, num_simulations),
        dtype=np.float32
      )
      KKPSPLUS_mean = 0.0193
      kkpplus_managementfee = 0.00383
      kkpsplus_dailyrate = (1+KKPSPLUS_mean) **(1/252)

      KKPCASH_mean = 0.0133
      kkpcash_managementfee =  0.0029
      kkpcash_dailyrate = (1+KKPCASH_mean)**(1/252)

      kfafix_year = 0.0196
      kfafix_dailyrate = (1+kfafix_year)**(1/1260)
      kfa_mangementfee = 0.0041

      ugisfx_year = 0.0686
      ugisfx_dailyrate = (1+ugisfx_year)**(1/252)
      ugisfx_managementfee = 0.0085

      esgqg_year = 0.1332
      esgqg_dailyrate = (1+esgqg_year)**(1/252)
      esgqg_managementfee = 0.0178

      esgtech_yr = 0.4269
      esgtech_dailyrate = (1+esgtech_yr)**(1/756)
      esgtech_managementfee = 0.0121

      eseae_yr = 0.1767
      eseae_dailyrate = (1+eseae_yr)**(1/756)
      eseae_managementfee = 0.0178

      ktprecious_3yr = 0.4149
      ktprecious_dailyrate = (1+ktprecious_3yr)**(1/756)
      ktprecious_managementfee = 0.0134

      savings_alloc = (
        1 -
          (
            kkpplus_alloc +
            kkpcash_alloc +
            kfa_alloc +
            ugi_alloc +
            gqg_alloc +
            gtech_alloc +
            eae_alloc +
            ktprecious_alloc
          )
      )
      trials_failed = 0
      total_funds = initial_amount
      inserted_funds = monthly_contribution
      yearly_withdrawals = withdrawal
      for sim in range(num_simulations):
        kfa_amt = kfa_alloc * total_funds
        ugi_amt = ugi_alloc * total_funds
        kkpplus_amt = kkpplus_alloc * total_funds
        kkpcash_amt = kkpcash_alloc * total_funds
        gqg_amt = gqg_alloc * total_funds
        gtech_amt = gtech_alloc * total_funds
        eae_amt = eae_alloc * total_funds
        ktp_amt = ktprecious_alloc * total_funds
        savings_amt = savings_alloc * total_funds
        equity_factor = t.rvs(df, loc=0, scale=equity_vol, size=days)

        gqg_rate    = 1.0 * equity_factor
        gtech_rate  = 1.25 * equity_factor
        eae_rate    = 1.15 * equity_factor

        bond_factor = t.rvs(df, loc=0, scale=bond_vol, size=days)

        kkpcash_rate = 0.05 * bond_factor
        kkpplus_rate = 0.15 * bond_factor
        kfa_rate     = 0.2 * bond_factor
        ugi_rate     = 1.00 * bond_factor

        commodity_factor = t.rvs(df, loc=0, scale=cmod_vol, size=days)

        ktp_rate = 1.5 * commodity_factor

        kkpplus_truerate = kkpplus_rate + kkpsplus_dailyrate
        kkpcash_truerate = kkpcash_rate + kkpcash_dailyrate
        kfa_truerate = kfa_rate + kfafix_dailyrate
        ugi_truerate = ugi_rate + ugisfx_dailyrate
        gqg_truerate = gqg_rate + esgqg_dailyrate
        gtech_truerate = gtech_rate + esgtech_dailyrate
        eae_truerate = eae_rate + eseae_dailyrate
        ktp_truerate = ktp_rate + ktprecious_dailyrate

        portfolio_path,failed = sim_path(
            kfa_truerate,
            ugi_truerate,
            gqg_truerate,
            kkpplus_truerate,
            kkpcash_truerate,
            gtech_truerate,
            eae_truerate,
            ktp_truerate,
            days,
            inserted_funds,
            yearly_withdrawals,
            gqg_amt,
            kkpplus_amt,
            kkpcash_amt,
            kfa_amt,
            ugi_amt,
            gtech_amt,
            eae_amt,
            ktp_amt,
            savings_amt,
            kkpplus_alloc,
            kkpcash_alloc,
            kfa_alloc,
            ugi_alloc,
            gqg_alloc,
            gtech_alloc,
            eae_alloc,
            ktprecious_alloc,
            savings_alloc
        )
        portfolio_simulations[:,sim] = portfolio_path
        trials_failed += failed
      percentiles = np.percentile(
        portfolio_simulations,
        [10,25,50,75,90],
        axis=1
        )
      fig, ax = plt.subplots(
          figsize=(12,7)
      )

      ax.plot(percentiles[0], label="10th")
      ax.plot(percentiles[1], label="25th")
      ax.plot(percentiles[2], label="50th")
      ax.plot(percentiles[3], label="75th")
      ax.plot(percentiles[4], label="90th")

      ax.legend()

      ax.set_title(
          "Portfolio Projection"
      )

      ax.set_xlabel(
          "Days"
      )

      ax.set_ylabel(
          "THB"
      )
      from matplotlib.ticker import FuncFormatter

      ax.yaxis.set_major_formatter(
        FuncFormatter(lambda x, pos: f"฿{x/1_000_000:.1f}M")
      )

      ax.set_ylabel("Portfolio Value (Million THB)")

      ax.grid(True)

      st.pyplot(fig)

      duration = days

      c1,c2,c3 = st.columns(3)
      ending_values = portfolio_simulations[-1, :]

      median = np.percentile(
        ending_values,
        50
      )

      c2.metric(
          "Median",
          f"฿{median/((1+avg_inflation_rate)**(duration/252)):,.0f}"
      )

      failure_rate = (
          trials_failed /
          num_simulations
      ) * 100

      st.metric(
          "Portfolio Failure Rate",
          f"{failure_rate:.2f}%"
      )

      success_rate = np.mean(
      (num_simulations-trials_failed)/num_simulations
      ) * 100

      c1.metric(
      "Capital Preserved",
      f"{success_rate:.1f}%"
      )



st.sidebar.title("Retirement Simulator")

model_type = st.sidebar.radio(
    "Model Type",
    [
        "Market Index Based Portfolio Model",
        "Bluebell Offered Mutual Funds Model"
    ]
)

if model_type == "Market Index Based Portfolio Model":
    run_index_model()

else:
    run_company_model()
