# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0rx4c2G6QB1UKgmNjVJ8PYunhInd8uN
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from numba import njit

# ==========================================
# 1. CACHED DATA FETCHING (PREVENTS API BANS)
# ==========================================
@st.cache_data(ttl=86400) # Cache for 24 hours
def fetch_and_prep_data(start_date='2000-01-01', end_date='2025-12-31'):
    tickers = ['^GSPC', '^SET.BK', '000001.SS', 'AGG', 'AOA', 'AOR', 'AOK']

    # Download all at once
    data = yf.download(tickers, start=start_date, end=end_date)['Close']
    data_change = np.log(data / data.shift(1)).dropna()

    # Isolate Bear/Bull periods for covariance matrices
    bear_data = data_change.loc['2007-01-01':'2010-01-01']
    bull_data = data_change.loc['2011-01-01':'2019-01-01']

    bfr_mean_returns = data_change.mean().values
    variances = np.diag(data_change.cov().values)
    mean_returns = bfr_mean_returns - (variances / 2) # Geometric adjust

    bull_cov = bull_data.cov().values
    bear_cov = bear_data.cov().values

    return mean_returns, bull_cov, bear_cov

# ==========================================
# 2. NUMBA JIT-COMPILED SIMULATION ENGINE
# ==========================================
# We compile the brutal nested loop logic to C-level speed.
# Pure Python takes minutes. Numba takes milliseconds.
@njit
def run_fast_simulations(num_simulations, duration, initial_amount, stock_alloc, fund_alloc,
                         savings_weight, pure_cash_weight, saving_daily_return,
                         bull_multipliers, bear_multipliers, withdrawal_amount, inserted_funds):

    portfolio_simulations = np.zeros((duration, num_simulations))
    trials_failed = 0

    # Flatten allocations for easier indexing
    us_weight, thai_weight, china_weight = stock_alloc
    bond_mut, agg_mut, mod_mut, con_mut = fund_alloc

    for sim in range(num_simulations):
        # Initial Balances
        us_stocks = initial_amount * us_weight
        thai_stocks = initial_amount * thai_weight
        china_stocks = initial_amount * china_weight
        bond_mutual = initial_amount * bond_mut
        agg_mutual = initial_amount * agg_mut
        mod_mutual = initial_amount * mod_mut
        con_mutual = initial_amount * con_mut
        savings = initial_amount * savings_weight
        pure_cash = initial_amount * pure_cash_weight

        is_bear = np.random.rand() < 0.5

        for day in range(duration):
            # Market Regime Switching
            if is_bear:
                mults = bear_multipliers[day, sim]
                if np.random.rand() < 0.1: is_bear = False
            else:
                mults = bull_multipliers[day, sim]
                if np.random.rand() < 0.05: is_bear = True

            # Apply Returns
            us_stocks *= mults[0]
            thai_stocks *= mults[1]
            china_stocks *= mults[2]
            bond_mutual *= mults[3]
            agg_mutual *= mults[4]
            mod_mutual *= mults[5]
            con_mutual *= mults[6]
            savings *= saving_daily_return

            # Monthly Injections
            if day > 0 and day % 21 == 0:
                us_stocks += inserted_funds * us_weight
                thai_stocks += inserted_funds * thai_weight
                china_stocks += inserted_funds * china_weight
                bond_mutual += inserted_funds * bond_mut
                agg_mutual += inserted_funds * agg_mut
                mod_mutual += inserted_funds * mod_mut
                con_mutual += inserted_funds * con_mut
                savings += inserted_funds * savings_weight

                # Withdrawals (The sequential drain logic you requested)
                # Draining in order: Cash -> Savings -> Aggressive -> Mod -> Con -> Bond -> Equity
                if day > 2520: # Assuming withdrawals start after phase 1
                    if pure_cash >= withdrawal_amount: pure_cash -= withdrawal_amount
                    elif savings >= withdrawal_amount: savings -= withdrawal_amount
                    elif agg_mutual >= withdrawal_amount: agg_mutual -= withdrawal_amount
                    elif mod_mutual >= withdrawal_amount: mod_mutual -= withdrawal_amount
                    elif con_mutual >= withdrawal_amount: con_mutual -= withdrawal_amount
                    elif bond_mutual >= withdrawal_amount: bond_mutual -= withdrawal_amount
                    elif us_stocks >= withdrawal_amount: us_stocks -= withdrawal_amount
                    else:
                        trials_failed += 1
                        break # Bankrupt

            portfolio_simulations[day, sim] = (us_stocks + thai_stocks + china_stocks +
                                               bond_mutual + agg_mutual + mod_mutual +
                                               con_mutual + savings + pure_cash)

    return portfolio_simulations, trials_failed

# ==========================================
# 3. STREAMLIT UI & ORCHESTRATION
# ==========================================
st.set_page_config(page_title="Ruthless Portfolio Engine", layout="wide")
st.title("Monte Carlo Portfolio Projection")

# Fetch data (Cached)
with st.spinner("Fetching historical market data..."):
    mean_returns, bull_cov, bear_cov = fetch_and_prep_data()

# Build the UI Sidebar replacing your 'input()' calls
st.sidebar.header("Portfolio Parameters")
initial_amount = st.sidebar.number_input("Initial Investment (THB)", value=3000000, step=100000)
inserted_funds = st.sidebar.number_input("Monthly Income Added", value=10000, step=1000)
withdrawal_pct = st.sidebar.number_input("Annual Withdrawal Rate (%)", value=4.0, step=0.1) / 100
withdrawal_amount = (initial_amount * withdrawal_pct) / 12

st.sidebar.header("Allocations (Must sum to <= 1.0)")
savings_weight = st.sidebar.slider("Savings Account Weight", 0.0, 1.0, 0.1)
us_weight = st.sidebar.slider("US Stock Weight", 0.0, 1.0, 0.1)
thai_weight = st.sidebar.slider("Thai Stock Weight", 0.0, 1.0, 0.2)
china_weight = st.sidebar.slider("China Stock Weight", 0.0, 1.0, 0.1)
bond_mut = st.sidebar.slider("Bond Mutual Fund", 0.0, 1.0, 0.1)
agg_mut = st.sidebar.slider("Aggressive Hybrid", 0.0, 1.0, 0.1)
mod_mut = st.sidebar.slider("Moderate Hybrid", 0.0, 1.0, 0.1)
con_mut = st.sidebar.slider("Conservative Hybrid", 0.0, 1.0, 0.1)

total_weight = sum([savings_weight, us_weight, thai_weight, china_weight, bond_mut, agg_mut, mod_mut, con_mut])
pure_cash_weight = 1.0 - total_weight

if total_weight > 1.0:
    st.sidebar.error(f"Weights exceed 1.0! Current: {total_weight:.2f}")
    st.stop()

st.sidebar.write(f"Remaining pure cash allocation: **{pure_cash_weight:.2%}**")

# Execution Trigger
if st.button("Run Simulation Engine"):
    duration = 7560
    num_sims = 1000

    # Pre-generate standard normal variables for speed
    # We do this in NumPy because Numba doesn't natively support multivariate_normal
    with st.spinner("Generating stochastic market paths..."):
        # Cholesky decomposition to map standard normals to our covariance matrix
        bull_chol = np.linalg.cholesky(bull_cov)
        bear_chol = np.linalg.cholesky(bear_cov)

        rand_normals = np.random.standard_normal((duration, num_sims, len(mean_returns)))

        # Apply Cholesky and Means
        bull_returns = rand_normals @ bull_chol.T + mean_returns
        bear_returns = rand_normals @ bear_chol.T + mean_returns

        # Apply fee drags
        expense_ratios = np.array([0.001, 0.002, 0.005, 0.001, 0.003, 0.003, 0.003])
        daily_fee_drag = (1 - expense_ratios) ** (1 / 252)

        bull_multipliers = np.exp(bull_returns) * daily_fee_drag
        bear_multipliers = np.exp(bear_returns) * daily_fee_drag

    with st.spinner("Executing Monte Carlo paths (Numba JIT)..."):
        stock_alloc = np.array([us_weight, thai_weight, china_weight])
        fund_alloc = np.array([bond_mut, agg_mut, mod_mut, con_mut])
        saving_daily_return = (1 + 0.025) ** (1 / 252)

        # Execute the compiled loop
        sim_results, trials_failed = run_fast_simulations(
            num_sims, duration, initial_amount, stock_alloc, fund_alloc,
            savings_weight, pure_cash_weight, saving_daily_return,
            bull_multipliers, bear_multipliers, withdrawal_amount, inserted_funds
        )

    # ==========================================
    # 4. VISUALIZATION & OUTPUT
    # ==========================================
    st.subheader("Simulation Results")
    col1, col2, col3 = st.columns(3)

    ending_values = sim_results[-1, :]
    col1.metric("Median Final Value", f"THB {np.percentile(ending_values, 50):,.2f}")
    col2.metric("Failed Scenarios", f"{(trials_failed/num_sims)*100:.1f}%")

    avg_inflation_rate = 0.0177
    adj_median = np.percentile(ending_values, 50) / ((1 + avg_inflation_rate) ** (duration / 252))
    col3.metric("Inflation Adjusted Median", f"THB {adj_median:,.2f}")

    # Matplotlib Fan Chart
    fig, ax = plt.subplots(figsize=(10, 5))
    percentiles = np.percentile(sim_results, [10, 25, 50, 75, 90], axis=1)

    ax.plot(percentiles[0], label='10th Percentile', color='red', linestyle='--')
    ax.plot(percentiles[1], label='25th Percentile', color='orange', linestyle=':')
    ax.plot(percentiles[2], label='50th Percentile', color='black', linewidth=2)
    ax.plot(percentiles[3], label='75th Percentile', color='green', linestyle=':')

    ax.set_title('Portfolio Value Projection (7560 Days)')
    ax.set_xlabel('Days')
    ax.set_ylabel('Portfolio Value (THB)')
    ax.legend(loc='upper left')
    ax.grid(True, alpha=0.3)

    st.pyplot(fig)