# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1192eau8Gwhpu4wiZKgWV-HVQtS-QvzkB
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numba import njit
import random
from scipy.stats import multivariate_t
from scipy.stats import t
from numba import njit

st.set_page_config(
    page_title="Monte Carlo Retirement Simulator",
    layout="wide"
)

st.title("Monte Carlo Portfolio Simulator")

st.write("This simulator is meant to help gague model effectiveness and may not always be reliable, hence, model outputs is not financial advice. "
            " Please interpret results with caution as model outputs may not reflect reality. The model is based on a retirement plan that consists of an accumulation phase, during which a monthly DCA can be added, followed by a retirement phase where funds are withdrew from the portfolio at a specificed fixed annual rate. The model also performs quarterly rebalancing to maintain the allocations that the user inputs. The industry standard for a good retirement plan is around an 80-90% success rate. For those who are more open to adjusting their lifestyles a 65-80% success rate may be viable.")
initial_amount = st.sidebar.number_input(
    "Initial Amount",
    0,
    100000000,
    1000000,
    1000000
)

monthly_contribution = st.sidebar.number_input(
    "Monthly Contribution",
    0,
    300000,
    10000
)

num_simulations = st.sidebar.slider(
    "Simulations",
    100,
    1000,
    250,
    10
)

withdrawal = st.sidebar.number_input(
    "Annual Withdrawal",
    0,
    3000000,
    10000

)

avg_inflation_rate = st.sidebar.slider(
    "Average Inflation Rate",
    0.0,
    0.15,
    0.02,
    0.01
)

target = st.sidebar.number_input(
    "Target Retirement Wealth",
    0,
    100_000_000,
    5_000_000
)

acum_years = st.sidebar.number_input(
    "Years Until Retirement",
    0,
    100,
    1
)

age_years = st.sidebar.number_input(
    "Your Age",
    0,
    100,
    1
)
def run_index_model():
  @st.cache_data
  def load_market_data():

      return pd.read_parquet(
          "1.parquet"
      )
  @st.cache_data
  def build_market_stats():

      combined_data = load_market_data()

      bear_data = combined_data.loc[
          "2005-01-01":"2009-04-01"
      ]

      bull_data = combined_data.loc[
          "2010-03-01":"2019-01-01"
      ]

      bull_mean = bull_data.mean()
      bear_mean = bear_data.mean()

      bull_cov = bull_data.cov()
      bear_cov = bear_data.cov()

      bull_var = np.diag(bull_cov)
      bear_var = np.diag(bear_cov)

      bull_adj = bull_mean - bull_var / 2
      bear_adj = bear_mean - bear_var / 2

      return (
          bull_adj.values,
          bear_adj.values,
          bull_cov.values,
          bear_cov.values
      )
  retirement_years = 85 - (age_years + acum_years)
  if retirement_years <= 0:
    st.error("Change your age to be under 85 for feasibility")
    st.stop()
  time_period = acum_years + retirement_years
  st.sidebar.subheader("Portfolio")

  us_weight = st.sidebar.slider(
      "US Equity",
      0.0,
      1.0,
      0.20,
      0.01
  )

  thai_weight = st.sidebar.slider(
      "Thai Equity",
      0.0,
      1.0,
      0.20,
      0.01
  )

  china_weight = st.sidebar.slider(
      "Chinese Equity",
      0.0,
      1.0,
      0.10,
      0.01
  )

  bond_weight = st.sidebar.slider(
      "Bond Fund",
      0.0,
      1.0,
      0.20,
      0.01
  )

  agg_weight = st.sidebar.slider(
      "Aggressive Hybrid Fund",
      0.0,
      1.0,
      0.10,
      0.01
  )

  mod_weight = st.sidebar.slider(
      "Moderate Hybrid Fund",
      0.0,
      1.0,
      0.10,
      0.01
  )

  cons_weight = st.sidebar.slider(
      "Conservative Hybrid Fund",
      0.0,
      1.0,
      0.05,
      0.01
  )

  savings_weight = st.sidebar.slider(
      "Savings",
      0.0,
      1.0,
      0.05,
      0.01
  )
  total_weight = (
      us_weight +
      thai_weight +
      china_weight +
      bond_weight +
      agg_weight +
      mod_weight +
      cons_weight +
      savings_weight
  )

  st.sidebar.write(
      f"Total Weight: {total_weight:.2f}"
  )

  if total_weight > 1:
      st.error(
          "Weights exceed 100%"
      )
      st.stop()
  import pandas as pd
  import plotly.express as px

  allocation_data = pd.DataFrame({
    "Asset": [
        "US Equity",
        "Thai Equity",
        "China Equity",
        "Bond Mutual Fund",
        "Aggresive Hybrid Mutual Fund",
        "Moderate Hybrid Mutual Fund",
        "Conservative Hybrid Mutual Fund",
        "Savings Account"
    ],
    "Allocation": [
        us_weight,
        thai_weight,
        china_weight,
        bond_weight,
        agg_weight,
        mod_weight,
        cons_weight,
        savings_weight,
        ]
    })

  allocation_data = allocation_data[
        allocation_data["Allocation"] > 0
  ]
  run = st.button(
      "Run Simulation"
  )
  @njit(cache=True)
  def run_path(
      acum_years,
      bull_mult,
      bear_mult,
      duration,
      matured_duration,
      assets,
      savings_account,
      pure_cash_amt,
      contribution_weights,
      inserted_funds,
      savings_account_weight,
      saving_daily_return,
      withdrawal_percentage,
      daily_hazard_rate,
      pure_cash_weight,

      us_gov_bond,
      us_inv_bond,
      us_spec_bond,
      thai_gov_bond,
      thai_inv_bond,
      thai_spec_bond,

      us_gov_bond_daily_return,
      us_inv_bond_daily_return,
      us_spec_bond_daily_return,
      thai_gov_bond_daily_return,
      thai_inv_bond_daily_return,
      thai_spec_bond_daily_return,

      stock_allocations,
      bond_mutualfund_allocation,
      hybrid_mutualfund_aggresive_allocation,
      hybrid_mutualfund_moderate_allocation,
      hybrid_mutualfund_conservative_allocation
  ):

      portfolio_path = np.zeros(duration, dtype=np.float32)

      thai_default_events = False
      us_default_events = False
      matured = False

      market = np.random.randint(0, 2)

      failed = 0

      for day in range(duration):

          if market == 1:

              current = bear_mult[day]

              if np.random.random() < 0.05:
                  market = 0

          else:

              current = bull_mult[day]

              if np.random.random() < 0.02:
                  market = 1

          assets *= current

          savings_account *= saving_daily_return

          if day < acum_years * 252:

              if (not thai_default_events) and np.random.random() < daily_hazard_rate:
                  thai_default_events = True

              if (not us_default_events) and np.random.random() < daily_hazard_rate:
                  us_default_events = True

          if not matured:

              us_gov_bond *= us_gov_bond_daily_return
              us_inv_bond *= us_inv_bond_daily_return
              thai_gov_bond *= thai_gov_bond_daily_return
              thai_inv_bond *= thai_inv_bond_daily_return

              if thai_default_events:
                  thai_spec_bond = 0.0
              else:
                  thai_spec_bond *= thai_spec_bond_daily_return

              if us_default_events:
                  us_spec_bond = 0.0
              else:
                  us_spec_bond *= us_spec_bond_daily_return

          if day % 21 == 0:

              if day < acum_years * 252:
                  pure_cash_amt += inserted_funds*pure_cash_weight
                  assets += inserted_funds * contribution_weights
                  savings_account += inserted_funds * savings_account_weight

              else:

                  withdrawal_amount = withdrawal_percentage / 12.0

                  if pure_cash_amt >= withdrawal_amount:

                      pure_cash_amt -= withdrawal_amount

                  elif savings_account >= withdrawal_amount:

                      savings_account -= withdrawal_amount

                  elif assets[4] >= withdrawal_amount:

                      assets[4] -= withdrawal_amount

                  elif assets[5] >= withdrawal_amount:

                      assets[5] -= withdrawal_amount

                  elif assets[6] >= withdrawal_amount:

                      assets[6] -= withdrawal_amount

                  elif assets[3] >= withdrawal_amount:

                      assets[3] -= withdrawal_amount

                  elif assets[0] >= withdrawal_amount:

                      assets[0] -= withdrawal_amount

                  elif assets[2] >= withdrawal_amount:

                      assets[2] -= withdrawal_amount

                  elif assets[1] >= withdrawal_amount:

                      assets[1] -= withdrawal_amount

                  else:

                      failed = 1
                      break

          if (not matured) and day > 0 and day % matured_duration == 0:

              matured = True

              pure_cash_amt += (
                  us_gov_bond
                  + us_inv_bond
                  + thai_gov_bond
                  + thai_inv_bond
                  + thai_spec_bond
                  + us_spec_bond
              )

              us_gov_bond = 0.0
              us_inv_bond = 0.0
              thai_gov_bond = 0.0
              thai_inv_bond = 0.0
              thai_spec_bond = 0.0
              us_spec_bond = 0.0
          if day% 63 == 0:
              cur_amount = pure_cash_amt + savings_account + assets.sum()
              pure_cash_amt = cur_amount * pure_cash_weight
              savings_account = cur_amount * savings_account_weight
              assets = np.array([
                    cur_amount * stock_allocations[0],
                    cur_amount * stock_allocations[1],
                    cur_amount * stock_allocations[2],
                    cur_amount * bond_mutualfund_allocation,
                    cur_amount * hybrid_mutualfund_aggresive_allocation,
                    cur_amount * hybrid_mutualfund_moderate_allocation,
                    cur_amount * hybrid_mutualfund_conservative_allocation
          ], dtype=np.float64)
                  

          portfolio_path[day] = (
              assets[0]
              + assets[1]
              + assets[2]
              + assets[3]
              + assets[4]
              + assets[5]
              + assets[6]
              + savings_account
              + pure_cash_amt
          )
              
      return portfolio_path,failed
  us_gov_bond_weight = 0.0
  us_inv_bond_weight = 0.0
  us_spec_bond_weight = 0.0

  thai_gov_bond_weight = 0.0
  thai_inv_bond_weight = 0.0
  thai_spec_bond_weight = 0.0
  if run:

      with st.spinner(
          "Running simulation..."
      ):
        expense_ratios = np.array([
        0.001,
        0.002,
        0.005,
        0.001,
        0.003,
        0.003,
        0.003
        ])

        daily_fee_drag = (1 - expense_ratios) ** (1/252)
        bull_adj_return, bear_adj_return, bull_cov_matrix, bear_cov_matrix = build_market_stats()
        stock_allocations = np.array([
          us_weight,
          thai_weight,
          china_weight
          ])

        bond_mutualfund_allocation = bond_weight
        hybrid_mutualfund_aggresive_allocation = agg_weight
        hybrid_mutualfund_moderate_allocation = mod_weight
        hybrid_mutualfund_conservative_allocation = cons_weight
        duration = (acum_years + retirement_years) * 252
        portfolio_simulations = np.zeros(
          (duration, num_simulations),
          dtype=np.float32
        )
        trials_failed = 0
        saving_returns = 0.0175
        drawdowns = []
        saving_daily_return = (1 + saving_returns) ** (1/252)
        withdrawal_percentage = withdrawal
        contribution_weights = np.array([
          us_weight,
          thai_weight,
          china_weight,
          bond_weight,
          agg_weight,
          mod_weight,
          cons_weight
        ], dtype=np.float64)
        inserted_funds = monthly_contribution

        daily_hazard_rate = 0.00011

        total_stock_weight = (
          us_weight +
          thai_weight +
          china_weight
      )

        total_mutualfund_weight = (
          bond_weight +
          agg_weight +
          mod_weight +
          cons_weight
        )

        us_gov_bond_return = 0.04
        us_inv_bond_return = 0.05
        us_spec_bond_return = 0.08

        thai_gov_bond_return = 0.045
        thai_inv_bond_return = 0.05
        thai_spec_bond_return = 0.08

        total_bond_weight = 0.0

        savings_account_weight = savings_weight
        for sim in range(num_simulations):
          matured = False
          matured_duration = np.random.randint(504,2520)
          bull_returns = np.random.multivariate_normal(bull_adj_return, bull_cov_matrix, duration)
          df = 6
          scale_factor = np.sqrt(df / np.random.chisquare(df, duration))

          bull_daily_stock_returns_log = bull_returns * scale_factor[:, np.newaxis]

          bull_daily_stock_multipliers = np.exp(bull_daily_stock_returns_log) * daily_fee_drag
    #bear

          bear_returns = np.random.multivariate_normal(bear_adj_return, bear_cov_matrix, duration)
          df = 6
          scale_factor = np.sqrt(df / np.random.chisquare(df, duration))

          bear_daily_stock_returns_log = bear_returns * scale_factor[:, np.newaxis]


          bear_daily_stock_multipliers = np.exp(bear_daily_stock_returns_log) * daily_fee_drag

          assets = np.array([
            initial_amount * stock_allocations[0],
            initial_amount * stock_allocations[1],
            initial_amount * stock_allocations[2],
            initial_amount * bond_mutualfund_allocation,
            initial_amount * hybrid_mutualfund_aggresive_allocation,
            initial_amount * hybrid_mutualfund_moderate_allocation,
            initial_amount * hybrid_mutualfund_conservative_allocation
          ], dtype=np.float64)
          savings_account = initial_amount * savings_account_weight

          us_gov_bond = initial_amount * us_gov_bond_weight
          us_inv_bond = initial_amount * us_inv_bond_weight
          us_spec_bond = initial_amount * us_spec_bond_weight
          thai_gov_bond = initial_amount * thai_gov_bond_weight
          thai_inv_bond = initial_amount * thai_inv_bond_weight
          thai_spec_bond = initial_amount * thai_spec_bond_weight

          pure_cash = max(0,1 - total_bond_weight - total_stock_weight - total_mutualfund_weight - savings_account_weight)
          pure_cash_amt = initial_amount * pure_cash


    # Reset bond daily returns back to initial at the start of each simulation iteration
          us_gov_bond_daily_return = (1+us_gov_bond_return)**(1/252)
          us_inv_bond_daily_return = (1+us_inv_bond_return)**(1/252)
          thai_gov_bond_daily_return = (1+thai_gov_bond_return)**(1/252)
          thai_inv_bond_daily_return = (1+thai_inv_bond_return)**(1/252)
          thai_spec_bond_daily_return = (1+thai_spec_bond_return)**(1/252)
          us_spec_bond_daily_return = (1+us_spec_bond_return)**(1/252)


          portfolio_path, failed = run_path(
            acum_years,
            bull_daily_stock_multipliers,
            bear_daily_stock_multipliers,
            duration,
            matured_duration,
            assets,
            savings_account,
            pure_cash_amt,
            contribution_weights,
            inserted_funds,
            savings_account_weight,
            saving_daily_return,
            withdrawal_percentage,
            daily_hazard_rate,
            pure_cash,

            us_gov_bond,
            us_inv_bond,
            us_spec_bond,
            thai_gov_bond,
            thai_inv_bond,
            thai_spec_bond,

            us_gov_bond_daily_return,
            us_inv_bond_daily_return,
            us_spec_bond_daily_return,
            thai_gov_bond_daily_return,
            thai_inv_bond_daily_return,
            thai_spec_bond_daily_return,

            stock_allocations,
            bond_mutualfund_allocation,
            hybrid_mutualfund_aggresive_allocation,
            hybrid_mutualfund_moderate_allocation,
            hybrid_mutualfund_conservative_allocation
          )

          portfolio_simulations[:, sim] = portfolio_path

          trials_failed += failed
          path = portfolio_simulations[:, sim]
          running_max = np.maximum.accumulate(path)
          dd = np.min(path / running_max - 1)
          drawdowns.append(dd)

      median_dd = np.median(drawdowns)


      percentiles = np.percentile(
          portfolio_simulations,
          [10,25,50,75,90],
          axis=1
      )
      fig, ax = plt.subplots(
          figsize=(12,7)
      )
      ages = age_years + np.arange(duration) / 252

      import plotly.graph_objects as go
    
      fig = go.Figure()

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[4]/1000000,
        mode='lines',
        name='90th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[3]/1000000,
        mode='lines',
        name='75th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[2]/1000000,
        mode='lines',
        name='50th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[1]/1000000,
        mode='lines',
        name='25th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))
    
      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[0]/1000000,
        mode='lines',
        name='10th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))
        
      fig.update_layout(
        title="Nominal Portfolio Value Projection",
        xaxis_title="Age",
        yaxis_title="Portfolio Value (Million THB)",
        hovermode="x unified",
        height = 700
      )

      fig.add_vline(
        x=acum_years+age_years,
        line_dash="dash",
        annotation_text="Retirement"
      )

      fig.add_vline(
          x=85,
          line_dash = "dash",
          annotation_text = "Average Thai Lifespan"
      )
    
      st.plotly_chart(fig, use_container_width=True)

      pie_fig = px.pie(
        allocation_data,
        names="Asset",
        values="Allocation",
        title="Portfolio Allocation"
      )

      st.plotly_chart(
        pie_fig,
        use_container_width=True
      )

      import plotly.express as px
      ending_values = portfolio_simulations[-1, :]

      import plotly.graph_objects as go
      ending_values_m = ending_values / 1_000_000
      capped_values = np.minimum(ending_values_m, 120)

      fig_hist = go.Figure()

      fig_hist.add_trace(
        go.Histogram(
        x=capped_values,
        xbins=dict(
            start=0,
            end=120,
            size=5
            ),
        name="Final Portfolio Values"
       )
      )

      fig_hist.update_layout(
        title="Distribution of Final Portfolio Values",
        xaxis_title="Final Portfolio Value (Million THB)",
        yaxis_title="Number of Simulations",
        bargap=0.05
      )
      fig_hist.update_xaxes(
        tickmode="array",
        tickvals=list(range(0, 121, 20)),
        ticktext=[str(x) for x in range(0, 120, 20)] + ["120+"]
      )

      st.plotly_chart(fig_hist, use_container_width=True)


      c1,c2,c3= st.columns(3)
      ending_values = portfolio_simulations[-1, :]

      median = np.percentile(
        ending_values,
        50
      )

      c2.metric(
          "Median (Adjusted for Inflation)",
          f"฿{median/((1+avg_inflation_rate)**(duration/252)):,.0f}"
      )

      failure_rate = (
          trials_failed /
          num_simulations
      ) * 100

      c1.metric(
          "Portfolio Failure Rate",
          f"{failure_rate:.2f}%"
      )

      success_rate = np.mean(
      (num_simulations-trials_failed)/num_simulations
      ) * 100

      c1.metric(
      "Success Rate",
      f"{success_rate:.1f}%"
      )
      probability = (
         np.mean(ending_values >= target)
        * 100
      )
      c2.metric(
      "Probabiltiy of reaching retirement goal",
      f"{probability:.1f}%"
      )

      c3.metric(
        "Median Maximum Drawdown",
        f"{median_dd:.1%}"
        )
def run_company_model():
  @st.cache_data
  def get_data():
          import pandas as pd
          return pd.read_parquet(
          "3.parquet"
      )
  @st.cache_data
  def build_matrices():
    combined_data = get_data()
    bond_vol = combined_data["bond"].std()
    equity_vol = combined_data["equity"].std()
    cmod_vol = combined_data["cmod"].std()
    fof_vol = combined_data["fof"].std()
    return bond_vol, equity_vol, cmod_vol, fof_vol
  bond_vol, equity_vol, cmod_vol, fof_vol = build_matrices()
  retirement_years = 85 - (age_years + acum_years)
  if retirement_years <= 0:
    st.error("Change your age to be under 85 for feasibility")
    st.stop()
  available_funds = [
    "KKP Plus",
    "KKP Cash",
    "KFAFIX",
    "UGISFX",
    "ESGQG",
    "ESGTECH",
    "ESEAE",
    "KTPRECIOUS",
    "Rostrum Wisdom Fund of Funds",
    "KKPGNPH",
    "KTHEALTHCAREA",
    "KFGPROPA",
    "SCBS&P500A",
    "ESGCORE"
  ]
  preset = st.sidebar.radio(
    "Portfolio",
    ["Custom", "Bluebell Basic", "Bluebell Balance", "Bluebell Beyond"]
  )
  if preset == "Bluebell Basic":
      gnph_alloc = 0.0
      healthcarea_alloc = 0.05
      gtech_alloc = 0.05
      propa_alloc = 0.05
      kkpplus_alloc = 0.35
      kfa_alloc = 0.3
      ugi_alloc = 0.1
      kkpcash_alloc = 0
      gqg_alloc = 0
      eae_alloc = 0
      ktprecious_alloc = 0
      rostrum_alloc = 0
      sp500a_alloc = 0 
      gcore_alloc = 0.1
  elif preset == "Bluebell Balance":
      gnph_alloc = 0.0
      healthcarea_alloc = 0.05
      gtech_alloc = 0.05
      propa_alloc = 0.05
      kkpplus_alloc = 0.15
      kfa_alloc = 0.2
      ugi_alloc = 0.1
      kkpcash_alloc = 0
      gqg_alloc = 0
      eae_alloc = 0.05
      ktprecious_alloc = 0
      rostrum_alloc = 0
      sp500a_alloc = 0.1
      gcore_alloc = 0.25
  elif preset == "Bluebell Beyond":
      gnph_alloc = 0.0
      healthcarea_alloc = 0.1
      gtech_alloc = 0.1
      propa_alloc = 0.1
      kkpplus_alloc = 0.05
      kfa_alloc = 0.05
      ugi_alloc = 0.05
      kkpcash_alloc = 0
      gqg_alloc = 0
      eae_alloc = 0.1
      ktprecious_alloc = 0
      rostrum_alloc = 0
      sp500a_alloc = 0.1
      gcore_alloc = 0.35
  elif preset == "Custom":
      selected_funds = st.sidebar.multiselect(
        "Select Funds",
        available_funds,
        default=["KKP Plus","KKP Cash"]
      )
      if "KKP Plus" in selected_funds:
          kkpplus_alloc = st.sidebar.slider(
            "KKP Plus",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else: 
          kkpplus_alloc = 0

      if "KKP Cash" in selected_funds:
          kkpcash_alloc = st.sidebar.slider(
              "KKP Cash",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          kkpcash_alloc = 0

      if "KFAFIX" in selected_funds:
          kfa_alloc = st.sidebar.slider(
              "KFAFIX",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          kfa_alloc = 0

      if "UGISFX" in selected_funds:
          ugi_alloc = st.sidebar.slider(
              "UGISFX",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          ugi_alloc = 0

      if "ESGQG" in selected_funds:
          gqg_alloc = st.sidebar.slider(
              "ESGQG",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          gqg_alloc = 0

      if "ESGTECH" in selected_funds:
        gtech_alloc = st.sidebar.slider(
          "ESGTECH",
          0.0,
          1.0,
          0.10,
          0.01
        )
      else:
          gtech_alloc = 0

      if "ESEAE" in selected_funds:
          eae_alloc = st.sidebar.slider(
              "ESEAE",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          eae_alloc = 0

      if "KTPRECIOUS" in selected_funds:
          ktprecious_alloc = st.sidebar.slider(
              "KTPRECIOUS",
              0.0,
              1.0,
              0.10,
              0.01
          )
      else:
          ktprecious_alloc = 0 
      if "Rostrum Wisdom Fund of Funds" in selected_funds:
          rostrum_alloc = st.sidebar.slider(
              "Rostrum Grand Wisdom Fund of Funds",
              0.0,
              1.0,
              0.1,
              0.01
          ) 
      else:
          rostrum_alloc = 0
      if "KKPGNPH" in selected_funds:
          gnph_alloc = st.sidebar.slider(
              "KKPGNPH",
              0.0,
              1.0,
              0.1,
              0.01
          ) 
      else:
          gnph_alloc = 0 
      if "KTHEALTHCAREA" in selected_funds:
          healthcarea_alloc = st.sidebar.slider(
              "KTHEALTHCAREA",
              0.0,
              1.0,
              0.1,
              0.01
          )
      else:
          healthcarea_alloc = 0
      if "KFGPROPA" in selected_funds:
          propa_alloc = st.sidebar.slider(
              "KFGPROPA",
              0.0,
              1.0,
              0.1,
              0.01
          )
      else: 
          propa_alloc = 0
      if "SCBS&P500A" in selected_funds:
          sp500a_alloc = st.sidebar.slider(
              "SCBS&P500A",
              0.0,
              1.0,
              0.1,
              0.01
          ) 
      else:
          sp500a_alloc = 0
      if "ESGCORE" in selected_funds:
          gcore_alloc = st.sidebar.slider(
              "ESGCORE",
              0.0,
              1.0,
              0.1,
              0.01
          )
      else:
          gcore_alloc = 0
  total_alloc = (
    kkpplus_alloc +
    kkpcash_alloc +
    kfa_alloc +
    ugi_alloc +
    gqg_alloc +
    gtech_alloc +
    eae_alloc +
    ktprecious_alloc +
    rostrum_alloc + 
    gnph_alloc + 
    healthcarea_alloc + 
    propa_alloc + 
    sp500a_alloc +
    gcore_alloc
  )

  if total_alloc > 1:
    st.error("Allocations exceed 100%")
    st.stop()
  if initial_amount * rostrum_alloc < 3000000 and rostrum_alloc != 0:
    st.error("Minimum investment for Rostrum Grand Fund of Funds is 3 million THB")
    st.stop()
  run = st.button(
    "Run Simulation"
  )
  savings_alloc = (
        1 -
          (
            kkpplus_alloc +
            kkpcash_alloc +
            kfa_alloc +
            ugi_alloc +
            gqg_alloc +
            gtech_alloc +
            eae_alloc +
            ktprecious_alloc + 
            rostrum_alloc + 
            gnph_alloc +
            healthcarea_alloc + 
            propa_alloc + 
            sp500a_alloc +
            gcore_alloc
          )
  )
  import pandas as pd
  import plotly.express as px

  allocation_data = pd.DataFrame({
    "Asset": [
        "KKP Plus",
        "KKP Cash",
        "KFAFIX",
        "UGISFX",
        "ESGQG",
        "ESGTECH",
        "ESEAE",
        "KTPRECIOUS",
        "Savings",
        "Rostrum",
        "KKPGNPH",
        "KTHEALTHCAREA",
        "KFGPROPA",
        "SCBS&P500A",
        "ESGCORE"
    ],
  "Allocation": [
        kkpplus_alloc,
        kkpcash_alloc,
        kfa_alloc,
        ugi_alloc,
        gqg_alloc,
        gtech_alloc,
        eae_alloc,
        ktprecious_alloc,
        savings_alloc,
        rostrum_alloc,
        gnph_alloc,
        healthcarea_alloc,
        propa_alloc,
        sp500a_alloc,
        gcore_alloc
    ]
  })

  allocation_data = allocation_data[
    allocation_data["Allocation"] > 0
  ]
  if run:

    with st.spinner("Running simulation..."):

      @njit(cache=True)
      def sim_path(
        acum_years,
        kfa_returns,
        ugi_returns,
        gqg_returns,
        kkpplus_returns,
        kkpcash_returns,
        gtech_returns,
        eae_returns,
        ktp_returns,
        rostrum_returns,
        gnph_returns,
        healthcarea_returns,
        propa_returns,
        sp500a_returns,
        gcore_returns,
        duration,
        inserted_funds,
        yearly_withdrawals,

        gqg_amt,
        kkpplus_amt,
        kkpcash_amt,
        kfa_amt,
        ugi_amt,
        gtech_amt,
        eae_amt,
        ktp_amt,
        savings_amt,
        rostrum_amt,
        gnph_amt,
        healthcarea_amt,
        propa_amt,
        sp500a_amt,
        gcore_amt,

        kkpplus_alloc,
        kkpcash_alloc,
        kfa_alloc,
        ugi_alloc,
        gqg_alloc,
        gtech_alloc,
        eae_alloc,
        ktprecious_alloc,
        savings_alloc,
        rostrum_alloc,
        gnph_alloc,
        healthcarea_alloc,
        propa_alloc,
        sp500a_alloc,
        gcore_alloc
      ):
        portfolio_paths = np.zeros(duration)
        failed = 0 # Initialize failed variable
        for day in range(duration):
          gqg_amt = gqg_amt * (gqg_returns[day]) # Changed kfa_returns to gqg_returns
          gtech_amt = gtech_amt *(gtech_returns[day])
          eae_amt = eae_amt *(eae_returns[day])
          ktp_amt = ktp_amt * (ktp_returns[day])
          ugi_amt = ugi_amt * (ugi_returns[day])
          kkpplus_amt = kkpplus_amt * (kkpplus_returns[day])
          kkpcash_amt = kkpcash_amt * (kkpcash_returns[day])
          kfa_amt = kfa_amt * (kfa_returns[day])
          rostrum_amt = rostrum_amt * (rostrum_returns[day])
          gnph_amt = gnph_amt * (gnph_returns[day])
          healthcarea_amt = healthcarea_amt * (healthcarea_returns[day])
          propa_amt = propa_amt * (propa_returns[day])
          sp500a_amt = sp500a_amt * (sp500a_returns[day])
          gcore_amt = gcore_amt * (gcore_returns[day])
          savings_amt = savings_amt
          if day < acum_years*252 and day % 21 ==0:
            kkpplus_amt += inserted_funds*kkpplus_alloc
            kkpcash_amt += inserted_funds*kkpcash_alloc
            kfa_amt += inserted_funds*kfa_alloc
            ugi_amt += inserted_funds*ugi_alloc
            gqg_amt += inserted_funds * gqg_alloc
            gtech_amt += inserted_funds * gtech_alloc
            eae_amt += inserted_funds * eae_alloc
            ktp_amt += inserted_funds * ktprecious_alloc
            savings_amt += inserted_funds * savings_alloc
            rostrum_amt += inserted_funds * rostrum_alloc
            gnph_amt += inserted_funds * gnph_alloc
            healthcarea_amt += inserted_funds * healthcarea_alloc
            propa_amt += inserted_funds * propa_alloc
            sp500a_amt += inserted_funds * sp500a_alloc
            gcore_amt += inserted_funds * gcore_alloc
          if day > acum_years*252 and day %21 ==0:
            withdrawal_amount = yearly_withdrawals/12
            if savings_amt - withdrawal_amount > 0:
              savings_amt = savings_amt-withdrawal_amount
            elif kfa_amt - withdrawal_amount > 0:
              kfa_amt = kfa_amt - withdrawal_amount
            elif ugi_amt - withdrawal_amount > 0:
              ugi_amt = ugi_amt - withdrawal_amount
            elif kkpplus_amt - withdrawal_amount > 0:
              kkpplus_amt = kkpplus_amt - withdrawal_amount
            elif kkpcash_amt - withdrawal_amount > 0:
              kkpcash_amt = kkpcash_amt - withdrawal_amount
            elif gqg_amt - withdrawal_amount > 0:
              gqg_amt = gqg_amt - withdrawal_amount
            elif gtech_amt - withdrawal_amount > 0:
              gtech_amt = gtech_amt - withdrawal_amount
            elif eae_amt - withdrawal_amount > 0:
              eae_amt = eae_amt - withdrawal_amount
            elif gcore_amt - withdrawal_amount > 0:
                gcore_amt = gcore_amt - withdrawal_amount
            elif ktp_amt - withdrawal_amount > 0:
              ktp_amt = ktp_amt - withdrawal_amount
            elif rostrum_amt - withdrawal_amount > 0:
              rostrum_amt = rostrum_amt - withdrawal_amount
            elif gnph_amt - withdrawal_amount > 0:
                gnph_amt = gnph_amt - withdrawal_amount
            elif healthcarea_amt - withdrawal_amount > 0:
                healthcarea_amt = healthcarea_amt - withdrawal_amount
            elif propa_amt - withdrawal_amount > 0:
                propa_amt = propa_amt - withdrawal_amount
            elif sp500a_amt - withdrawal_amount >0:
                sp500a_amt = sp500a_amt - withdrawal_amount
            else:
              failed = 1
              break
          if day % 252 == 0:
            kkpplus_amt = kkpplus_amt * (1-kkpplus_managementfee)
            kkpcash_amt = kkpcash_amt * (1-kkpcash_managementfee)
            kfa_amt = kfa_amt * (1-kfa_mangementfee)
            ugi_amt = ugi_amt * (1-ugisfx_managementfee)
            gqg_amt = gqg_amt * (1-esgqg_managementfee)
            gtech_amt = gtech_amt * (1-esgtech_managementfee)
            eae_amt = eae_amt * (1-eseae_managementfee)
            ktp_amt = ktp_amt * (1-ktprecious_managementfee)
            rostrum_amt = rostrum_amt * (1-rostrum_managementfee)
            gnph_amt = gnph_amt * (1-gnph_managementfee)
            healthcarea_amt = healthcarea_amt * (1-healthcarea_managementfee)
            propa_amt = propa_amt * (1-propa_managementfee)
            sp500a_amt = sp500a_amt * (1-sp500a_managementfee)
            gcore_amt = gcore_amt * (1-gcore_managementfee)
          if day % 63 == 0:
              curnt_amt = kkpplus_amt+kkpcash_amt + kfa_amt + ugi_amt+ gqg_amt + gtech_amt + eae_amt + ktp_amt + rostrum_amt + gnph_amt + healthcarea_amt + propa_amt + sp500a_amt + savings_amt +gcore_amt
              kkpplus_amt = curnt_amt * kkpplus_alloc
              kkpcash_amt = curnt_amt * kkpcash_alloc
              kfa_amt = curnt_amt * kfa_alloc
              ugi_amt = curnt_amt * ugi_alloc
              gqg_amt = curnt_amt * gqg_alloc
              gtech_amt = curnt_amt * gtech_alloc
              eae_amt = curnt_amt * eae_alloc
              ktp_amt = curnt_amt * ktprecious_alloc
              savings_amt = curnt_amt * savings_alloc
              rostrum_amt = curnt_amt * rostrum_alloc
              gcore_amt = curnt_amt * gcore_alloc
              if rostrum_amt < 3000000 and rostrum_amt != 0:
                  if savings_amt - (3000000-rostrum_amt) > 0:
                      rostrum_amt = rostrum_amt + savings_amt
                  elif kkpplus_amt - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      kkpplus_amt = kkpplus_amt - (3000000-rostrum_amt)
                  elif kkpcash_amt - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      kkpcash_amt = kkpcash_amt - (3000000-rostrum_amt)
                  elif (kkpcash_amt + kkpplus_amt) - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      pool = (kkpcash_amt + kkpplus_amt) - (3000000-rostrum_amt)
                      kkpcash_amt = 0.5*pool
                      kkpplus_amt = 0.5*pool
                  elif kfa_amt - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      kfa_amt = kfa_amt - (3000000-rostrum_amt)
                  elif ugi_amt - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      ugi_amt = ugi_amt - (3000000-rostrum_amt)
                  elif (kfa_amt + ugi_amt) - (3000000-rostrum_amt) > 0:
                      rostrum_amt = 3000000
                      pool = (kfa_amt + ugi_amt) - (3000000-rostrum_amt)
                      kfa_amt = 0.5*pool
                      ugi_amt = 0.5*pool
                  else:
                      savings_amt = savings_amt + rostrum_amt
                      rostrum_amt = 0
              gnph_amt = curnt_amt * gnph_alloc
              healthcarea_amt = curnt_amt * healthcarea_alloc
              propa_amt = curnt_amt * propa_alloc
              sp500a_amt = curnt_amt * sp500a_alloc
          portfolio_paths[day] = (
              kkpplus_amt + kkpcash_amt + kfa_amt + ugi_amt + gqg_amt + gtech_amt + eae_amt + ktp_amt + savings_amt + rostrum_amt +gnph_amt + healthcarea_amt + propa_amt + sp500a_amt + gcore_amt
              )

        return portfolio_paths,failed
      days = (acum_years + retirement_years) * 252
      df = 10

      portfolio_simulations = np.zeros(
        (days, num_simulations),
        dtype=np.float32
      )
      KKPSPLUS_mean = 0.023533
      kkpplus_managementfee = 0.00383
      kkpsplus_dailyrate = (1+KKPSPLUS_mean) **(1/252)

      KKPCASH_mean = 0.0186
      kkpcash_managementfee =  0.0029
      kkpcash_dailyrate = (1+KKPCASH_mean)**(1/252)

      kfafix_year = 0.02357778
      kfafix_dailyrate = (1+kfafix_year)**(1/252)
      kfa_mangementfee = 0.0041

      ugisfx_year = 0.0473
      ugisfx_dailyrate = (1+ugisfx_year)**(1/252)
      ugisfx_managementfee = 0.0085

      esgqg_year = 0.09576
      esgqg_dailyrate = (1+esgqg_year)**(1/252)
      esgqg_managementfee = 0.0178

      esgtech_yr = 0.16656 * 0.6
      esgtech_dailyrate = (1+esgtech_yr)**(1/252)
      esgtech_managementfee = 0.0121

      eseae_yr = 0.0973
      eseae_dailyrate = (1+eseae_yr)**(1/252)
      eseae_managementfee = 0.0178

      ktprecious_yr = 0.10803
      ktprecious_dailyrate = (1+ktprecious_yr)**(1/252)
      ktprecious_managementfee = 0.0134

      rostrum_yr = 0.126*(1/3) + 0.13*(1/3) + 0.139*(1/3)
      rostrum_dailyrate = (1+rostrum_yr) ** (1/252)
      rostrum_managementfee = 0.015

      gnph_yr = 0.0978666
      gnph_dailyrate = (1+gnph_yr) ** (1/252)
      gnph_managementfee = 0.0175

      healthcarea_yr = 0.0725
      healthcarea_dailyrate = (1+healthcarea_yr) ** (1/252)
      healthcarea_managementfee = 0.0134

      propa_yr = 0.0835
      propa_dailyrate = (1+propa_yr) ** (1/252)
      propa_managementfee = 0.0154

      sp500a_yr = 0.078425
      sp500a_dailyrate = (1+sp500a_yr) ** (1/252)
      sp500a_managementfee = 0.011

      gcore_yr = 0.10132
      gcore_dailyrate = (1+gcore_yr) ** (1/252)
      gcore_managementfee = 0.0125

      savings_alloc = (
        1 -
          (
            kkpplus_alloc +
            kkpcash_alloc +
            kfa_alloc +
            ugi_alloc +
            gqg_alloc +
            gtech_alloc +
            eae_alloc +
            ktprecious_alloc + 
            rostrum_alloc + 
            gnph_alloc +
            healthcarea_alloc + 
            propa_alloc + 
            sp500a_alloc +
            gcore_alloc
          )
      )
      trials_failed = 0
      drawdowns = []
      total_funds = initial_amount
      inserted_funds = monthly_contribution
      yearly_withdrawals = withdrawal
      for sim in range(num_simulations):
        kfa_amt = kfa_alloc * total_funds
        ugi_amt = ugi_alloc * total_funds
        kkpplus_amt = kkpplus_alloc * total_funds
        kkpcash_amt = kkpcash_alloc * total_funds
        gqg_amt = gqg_alloc * total_funds
        gtech_amt = gtech_alloc * total_funds
        eae_amt = eae_alloc * total_funds
        ktp_amt = ktprecious_alloc * total_funds
        savings_amt = savings_alloc * total_funds
        rostrum_amt = rostrum_alloc * total_funds
        gnph_amt = gnph_alloc * total_funds
        healthcarea_amt = healthcarea_alloc * total_funds
        propa_amt = propa_alloc * total_funds
        sp500a_amt = sp500a_alloc * total_funds
        gcore_amt = gcore_alloc * total_funds
        equity_factor = t.rvs(df, loc=0, scale=equity_vol, size=days)

        gqg_rate    = 1.05 * equity_factor
        gtech_rate  = 1.45 * equity_factor
        eae_rate    = 1.25 * equity_factor
        gcore_rate = 1.1 * equity_factor
        gnph_rate  = 1.25 * equity_factor
        healthcarea_rate = 1.1 * equity_factor
        propa_rate = 1.1 * equity_factor
        sp500a_rate = 0.9 * equity_factor

        bond_factor = t.rvs(df, loc=0, scale=bond_vol, size=days)

        kkpcash_rate = 0.1 * bond_factor
        kkpplus_rate = 0.2 * bond_factor
        kfa_rate     = 0.25 * bond_factor
        ugi_rate     = 1.00 * bond_factor

        commodity_factor = t.rvs(df, loc=0, scale=cmod_vol, size=days)

        ktp_rate = 1.5 * commodity_factor

        fof_factor = t.rvs(df,loc=0,scale=fof_vol,size=days)

        rostrum_rate = 1.75 * fof_factor

        kkpplus_truerate = kkpplus_rate + kkpsplus_dailyrate
        kkpcash_truerate = kkpcash_rate + kkpcash_dailyrate
        kfa_truerate = kfa_rate + kfafix_dailyrate
        ugi_truerate = ugi_rate + ugisfx_dailyrate
        gqg_truerate = gqg_rate + esgqg_dailyrate
        gtech_truerate = gtech_rate + esgtech_dailyrate
        eae_truerate = eae_rate + eseae_dailyrate
        ktp_truerate = ktp_rate + ktprecious_dailyrate
        rostrum_truerate = rostrum_rate + rostrum_dailyrate
        gnph_truerate = gnph_rate + gnph_dailyrate
        healthcarea_truerate = healthcarea_rate + healthcarea_dailyrate
        propa_truerate = propa_rate + propa_dailyrate
        sp500a_truerate = sp500a_rate + sp500a_dailyrate
        gcore_truerate = gcore_rate + gcore_dailyrate

        portfolio_path,failed = sim_path(
            acum_years,
            kfa_truerate,
            ugi_truerate,
            gqg_truerate,
            kkpplus_truerate,
            kkpcash_truerate,
            gtech_truerate,
            eae_truerate,
            ktp_truerate,
            rostrum_truerate,
            gnph_truerate,
            healthcarea_truerate,
            propa_truerate,
            sp500a_truerate,
            gcore_truerate,
            days,
            inserted_funds,
            yearly_withdrawals,
            gqg_amt,
            kkpplus_amt,
            kkpcash_amt,
            kfa_amt,
            ugi_amt,
            gtech_amt,
            eae_amt,
            ktp_amt,
            savings_amt,
            rostrum_amt,
            gnph_amt,
            healthcarea_amt,
            propa_amt,
            sp500a_amt,
            gcore_amt,
            kkpplus_alloc,
            kkpcash_alloc,
            kfa_alloc,
            ugi_alloc,
            gqg_alloc,
            gtech_alloc,
            eae_alloc,
            ktprecious_alloc,
            savings_alloc,
            rostrum_alloc,
            gnph_alloc,
            healthcarea_alloc,
            propa_alloc,
            sp500a_alloc,
            gcore_alloc
        )
        portfolio_simulations[:,sim] = portfolio_path
        trials_failed += failed
        path = portfolio_simulations[:, sim]
        running_max = np.maximum.accumulate(path)
        dd = np.min(path / running_max - 1)
        drawdowns.append(dd)

      median_dd = np.median(drawdowns)
      percentiles = np.percentile(
        portfolio_simulations,
        [10,25,50,75,90],
        axis=1
        )
      ages = age_years + np.arange(days) / 252

      import plotly.graph_objects as go
    
      fig = go.Figure()

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[4]/1000000,
        mode='lines',
        name='90th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[3]/1000000,
        mode='lines',
        name='75th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[2]/1000000,
        mode='lines',
        name='50th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))  

      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[1]/1000000,
        mode='lines',
        name='25th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))
    
      fig.add_trace(go.Scatter(
        x=ages,
        y=percentiles[0]/1000000,
        mode='lines',
        name='10th Percentile',
        hovertemplate=
        'Year: %{x:.1f}<br>' +
        'Value: ฿%{y:,.2f}M<extra></extra>'
      ))
        
      fig.update_layout(
        title="Nominal Portfolio Value Projection",
        xaxis_title="Age",
        yaxis_title="Portfolio Value (Million THB)",
        hovermode="x unified",
        height = 700
      )
      fig.add_vline(
        x=acum_years+age_years,
        line_dash="dash",
        annotation_text="Retirement"
      )
      fig.add_vline(
          x=85,
          line_dash = "dash",
          annotation_text = "Average Thai Lifespan",
      )
    
      st.plotly_chart(fig, use_container_width=True)

      pie_fig = px.pie(
        allocation_data,
        names="Asset",
        values="Allocation",
        title="Portfolio Allocation"
      )

      st.plotly_chart(
        pie_fig,
        use_container_width=True
      )

      import plotly.express as px
      ending_values = portfolio_simulations[-1, :]
      import plotly.graph_objects as go
      ending_values_m = ending_values / 1_000_000
      capped_values = np.minimum(ending_values_m, 120)

      fig_hist = go.Figure()

      fig_hist.add_trace(
        go.Histogram(
        x=capped_values,
        xbins=dict(
            start=0,
            end=120,
            size=5
            ),
        name="Final Portfolio Values"
       )
      )

      fig_hist.update_layout(
        title="Distribution of Final Portfolio Values",
        xaxis_title="Final Portfolio Value (Million THB)",
        yaxis_title="Number of Simulations",
        bargap=0.05
      )
      fig_hist.update_xaxes(
        tickmode="array",
        tickvals=list(range(0, 121, 20)),
        ticktext=[str(x) for x in range(0, 120, 20)] + ["120+"]
      )

      st.plotly_chart(fig_hist, use_container_width=True)

      duration = days

      c1,c2,c3 = st.columns(3)
      ending_values = portfolio_simulations[-1, :]

      median = np.percentile(
        ending_values,
        50
      )

      c2.metric(
          "Median (Adjusted for Inflation)",
          f"฿{median/((1+avg_inflation_rate)**(duration/252)):,.0f}"
      )

      failure_rate = (
          trials_failed /
          num_simulations
      ) * 100

      c1.metric(
          "Portfolio Failure Rate",
          f"{failure_rate:.2f}%"
      )

      success_rate = np.mean(
      (num_simulations-trials_failed)/num_simulations
      ) * 100

      c1.metric(
      "Success Rate",
      f"{success_rate:.1f}%"
      )

      probability = (
         np.mean(ending_values >= target)
        * 100
      )
      c2.metric(
      "Probabiltiy of reaching retirement goal",
      f"{probability:.1f}%"
      )

      c3.metric(
        "Median Maximum Drawdown",
        f"{median_dd:.1%}"
        )

st.sidebar.title("Retirement Simulator")

model_type = st.sidebar.radio(
    "Model Type",
    [
        "Market Index Based Portfolio Model",
        "Bluebell Offered Mutual Funds Model"
    ]
)

if model_type == "Market Index Based Portfolio Model":
    run_index_model()

else:
    run_company_model()
