[theme]
base = "dark"
showSidebarBorder = true

chartCategoricalColors = [
    "#5D88BB",
    "#B3CBE4",
    "#7DA4CE",
    "#D6D6D6",
    "#A1A8B2",
    "#416B98",
    "#E5EEF7"
]

[theme.dark]
primaryColor = "#4F8CFF"
backgroundColor = "#050B18"
secondaryBackgroundColor = "#10233D"
textColor = "#F1F6FF"
borderColor = "#405A73"
showWidgetBorder = true
baseRadius = "large"
buttonRadius = "large"

[theme.light]
primaryColor = "#4F8CFF"
backgroundColor = "#050B18"
secondaryBackgroundColor = "#10233D"
textColor = "#F1F6FF"
borderColor = "#405A73"
showWidgetBorder = true
baseRadius = "large"
buttonRadius = "large"

[theme.dark.sidebar]
primaryColor = "#4F8CFF"
backgroundColor = "#071426"
secondaryBackgroundColor = "#10233D"
textColor = "#F1F6FF"
borderColor = "#405A73"

[theme.light.sidebar]
primaryColor = "#4F8CFF"
backgroundColor = "#071426"
secondaryBackgroundColor = "#10233D"
textColor = "#F1F6FF"
borderColor = "#405A73"
