[theme]
base = "light"

primaryColor = "#5D88BB"
backgroundColor = "#D6D6D6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#102336"
borderColor = "#A1A8B2"

showWidgetBorder = true
showSidebarBorder = true

baseRadius = "large"
buttonRadius = "large"

[theme.sidebar]
backgroundColor = "#B3CBE4"
secondaryBackgroundColor = "#FFFFFF"
primaryColor = "#5D88BB"
textColor = "#102336"
borderColor = "#A1A8B2"
